// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PE3.Pokemon.web.Data;

namespace PE3.Pokemon.web.Migrations
{
    [DbContext(typeof(PokemonContext))]
    [Migration("20181122163936_FirstPokemonMigration")]
    partial class FirstPokemonMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.1-rtm-30846")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("PE3.Pokemon.web.Entities.Pokemon", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Description");

                    b.Property<bool>("HasAllolanForm");

                    b.Property<string>("ImgUrl");

                    b.Property<string>("Location");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Pokemons");
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.PokemonType", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("TypeId");

                    b.HasKey("PokemonId", "TypeId");

                    b.HasIndex("TypeId");

                    b.ToTable("PokemonTypes");
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.PokemonUser", b =>
                {
                    b.Property<Guid>("PokemonId");

                    b.Property<Guid>("UserId");

                    b.HasKey("PokemonId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("PokemonUsers");
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.Type", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Types");

                    b.HasData(
                        new { Id = new Guid("0430a2a0-efe5-41ac-8564-b04876f08728"), Name = "Normal" },
                        new { Id = new Guid("c56cd56d-3642-4961-a8c6-8582e9676e1f"), Name = "Fighting" },
                        new { Id = new Guid("b6ae7c2a-c7b3-4a19-a1d2-4183195cc56c"), Name = "Flying" },
                        new { Id = new Guid("30899c17-15be-45ef-9730-511b6ce2ec16"), Name = "Poison" },
                        new { Id = new Guid("60c95187-9605-46b4-b214-8b4663bc8a2c"), Name = "Ground" },
                        new { Id = new Guid("f3e915dd-4be9-4211-b62e-d7b79ffd26c7"), Name = "Rock" },
                        new { Id = new Guid("6003ed6c-dad3-4f0a-905a-b4d9c4898dab"), Name = "Bug" },
                        new { Id = new Guid("e9970647-e3c4-40ae-98ad-aa752a4f6e22"), Name = "Ghost" },
                        new { Id = new Guid("850f62d6-6907-44a3-8a95-455063adcfc4"), Name = "Steel" },
                        new { Id = new Guid("11b6dcbb-14d2-4de8-9519-415dee8e3b6f"), Name = "Fire" },
                        new { Id = new Guid("ece96743-d4c6-4775-8b0a-7649f7cb9491"), Name = "Water" },
                        new { Id = new Guid("6e2fe5f7-7665-44a3-a137-576d209965ad"), Name = "Grass" },
                        new { Id = new Guid("7ce365ac-9862-4c36-ad44-c80be50c1beb"), Name = "Electric" },
                        new { Id = new Guid("af547cd3-1ddf-4e04-9f34-76bfe2e725ec"), Name = "Psychic" },
                        new { Id = new Guid("a8e26784-056c-4720-a412-f6de0f2ab3db"), Name = "Ice" },
                        new { Id = new Guid("ff3e6c5c-d2d4-470f-bf0b-0811240acdb0"), Name = "Dragon" },
                        new { Id = new Guid("e056d750-fbbd-435b-b3f2-7a9a12314030"), Name = "Dark" },
                        new { Id = new Guid("9993daeb-790c-4a28-be9e-28d96b53b68e"), Name = "Fairy" }
                    );
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("FirstName");

                    b.Property<string>("LastName");

                    b.Property<string>("Password");

                    b.Property<string>("Username");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.PokemonType", b =>
                {
                    b.HasOne("PE3.Pokemon.web.Entities.Pokemon", "Pokemon")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Pokemon.web.Entities.Type", "Type")
                        .WithMany("PokemonTypes")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("PE3.Pokemon.web.Entities.PokemonUser", b =>
                {
                    b.HasOne("PE3.Pokemon.web.Entities.Pokemon", "Pokemon")
                        .WithMany("PokemonUsers")
                        .HasForeignKey("PokemonId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("PE3.Pokemon.web.Entities.User", "User")
                        .WithMany("PokemonUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
